# Advanced Array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([1.5 , 2.5, 5, 6, 7])

print(a)
print(b)

[1 2 3 4 5]
[1.5 2.5 5.  6.  7. ]


In [3]:
c = np.arange(1,10,2)

print(c)

c_2 = np.arange(1, 10, 0.5)
print(c_2)

[1 3 5 7 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [4]:
d = np.linspace(1,10,4)

print(d)

[ 1.  4.  7. 10.]


In [5]:
# array multidimensi / matrix
e = np.array( [ (1,2,3) , 
                (4,5,6) ])

print(e)
print(e.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
# matrix dengan nilai nol
f = np.zeros((5,5))
print(f)
# matrix dengan nilai satu
g = np.ones((5,5))
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
h1 = np.identity(5)

print(h1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Operasi Matematika

In [21]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]

anp = np.array([1,2,3,4,5])
bnp = np.array([6,7,8,9,10])

anp + bnp

array([ 7,  9, 11, 13, 15])

In [22]:
ab = a + b
print(ab)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [10]:
anp - bnp

array([-5, -5, -5, -5, -5])

In [11]:
anp * bnp

array([ 6, 14, 24, 36, 50])

In [12]:
anp / bnp

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [13]:
anp**2

array([ 1,  4,  9, 16, 25])

In [14]:
c = np.array(([1,2,3],
              [4,5,6]))
d = np.array(([7,8,9],
              [-1,-2,-3]))

add = c + d
mult = c * d
print(add)
print(mult)

[[ 8 10 12]
 [ 3  3  3]]
[[  7  16  27]
 [ -4 -10 -18]]


In [23]:
2 * c

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
import sympy as sp

rational_c = sp.Rational(1, 2) * c
print(rational_c)

[[1/2 1 3/2]
 [2 5/2 3]]


# Perkalian Dot Matrix

In [15]:
a = np.array(([1,2],
              [3,4]))

b = np.ones([2,2])

print("matrix a:")
print(a)
print()

print("matrix b:")
print(b)
print()

# perkalian matrix
c1 = np.dot(a,b)
c2 = a.dot(b)

print("matrix c1:")
print(c1)
print()

print("matrix c2:")
print(c2)
print()

matrix a:
[[1 2]
 [3 4]]

matrix b:
[[1. 1.]
 [1. 1.]]

matrix c1:
[[3. 3.]
 [7. 7.]]

matrix c2:
[[3. 3.]
 [7. 7.]]



# Shape Manipulation

In [16]:
a = np.array((
            [1,2,3],
            [4,5,6]
))

print('matrix a dengan ukuran:',a.shape)
print(a)
print()


# transpose matrix
print('transpose matrix dari a:')
print(a.transpose())
print(a.shape)
print()

# transpose matrix
print('transpose matrix dari a transpose:')
a_transpose = np.transpose(a)
print(a_transpose.shape)
print()



matrix a dengan ukuran: (2, 3)
[[1 2 3]
 [4 5 6]]

transpose matrix dari a:
[[1 4]
 [2 5]
 [3 6]]
(2, 3)

transpose matrix dari a transpose:
(3, 2)



# Invers Matrix

In [17]:
a = np.array([
            (2,4),
            (3,5)])

print(a)
print()

# inverse matrix
a_inv = np.linalg.inv(a)

print(a_inv)
print()

# determinan matrix
det_a = np.linalg.det(a)
det_a_inv = np.linalg.det(a_inv)
print(det_a)
print(det_a_inv)


[[2 4]
 [3 5]]

[[-2.5  2. ]
 [ 1.5 -1. ]]

-2.000000000000001
-0.49999999999999967


# Contoh SPLDV

In [18]:
# 2a + 3b = 23 and a + 2b = 14

A = np.array([(2,3),
              (1,2)])

Y = np.array([23,14])

print(A)
print(Y)
print()

A_inv = np.linalg.inv(A)

# menyelesaikan persamaan linear
X1 = np.dot(A_inv,Y)
print(X1)
print()

# cara lain
X2 = np.linalg.solve(A,Y)
print(X2)


[[2 3]
 [1 2]]
[23 14]

[4. 5.]

[4. 5.]
